# Copyright 2025 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""07 — Iterate: data-driven component replication.

What you learn:
    - iterate='^path': replicate a component once per child in data
    - ^.?attr: resolve an attribute from the current data node
    - datapath: each iteration gets its own data namespace
    - Data is a Bag of nodes with attributes (loaded from JSON)
    - The component body uses relative pointers to access per-item data

Prerequisites: 05_components, 04_pointers

Usage:
    python 07_iterate.py
"""
from __future__ import annotations

from pathlib import Path

from genro_bag.resolvers import FileResolver

from genro_builders.builder import component
from genro_builders.contrib.html import HtmlBuilder
from genro_builders.manager import ReactiveManager

HERE = Path(__file__).parent


class CatalogBuilder(HtmlBuilder):
    """HtmlBuilder with a product_card component for iterate."""

    @component(main_tag='div', sub_tags='')
    def product_card(self, comp, **kwargs):
        """One product card. Replicated by iterate, one per data node."""
        card = comp.div(_class="card")
        card.h3("^.?name")
        card.p("^.?price", _class="price")
        card.p("^.?description")
        card.p("^.?category", _class="category")


class ProductCatalog(ReactiveManager):
    """Catalog page: iterate generates one card per product."""

    def on_init(self):
        self.page = self.register_builder("page", CatalogBuilder)

    def main(self, source):
        head = source.head()
        head.title("Product Catalog — Iterate")
        # FileResolver: pull model — content loaded on demand at render time
        head.style(FileResolver("style.css", base_path=str(HERE)))

        body = source.body()
        page = body.div(_class="page")
        page.h1("Product Catalog")
        page.p("Each card is generated by iterate — one per product in the data Bag.")

        catalog = page.div(_class="catalog")
        catalog.product_card(iterate="^products")


app = ProductCatalog()
# FileResolver with as_bag=True: Bag node format (label/value/attr) preserved
app.local_store("page").set_resolver(
    "products", FileResolver("products.json", as_bag=True, base_path=str(HERE)),
)
app.run()
html = app.page.render()

output = HERE / "07_iterate.html"
output.write_text(html)
print(html)
print(f"\nSaved to {output}")
