# Copyright 2025 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""07 — Iterate: data-driven component replication.

What you learn:
    - iterate='^path': replicate a component once per child in data
    - ^.?attr: resolve an attribute from the current data node
    - datapath: each iteration gets its own data namespace
    - The data is a Bag of nodes with attributes (set_item with kwargs)
    - The component body uses relative pointers to access per-item data

Prerequisites: 05_components, 04_pointers

Usage:
    python 07_iterate.py
"""
from __future__ import annotations

from pathlib import Path

from genro_bag import Bag

from genro_builders.builder import component
from genro_builders.contrib.html import HtmlBuilder
from genro_builders.manager import ReactiveManager


class CatalogBuilder(HtmlBuilder):
    """HtmlBuilder with a product_card component for iterate."""

    @component(main_tag='div', sub_tags='')
    def product_card(self, comp, **kwargs):
        """One product card. Replicated by iterate, one per data node."""
        card = comp.div(_class="card")
        card.h3("^.?name")
        card.p("^.?price", _class="price")
        card.p("^.?description")
        card.p("^.?category", _class="category")


class ProductCatalog(ReactiveManager):
    """Catalog page: iterate generates one card per product."""

    def __init__(self):
        self.page = self.set_builder("page", CatalogBuilder)

    def store(self, data):
        products = Bag()
        products.set_item(
            "p0", None,
            name="Wireless Headphones", price="$79.99",
            description="Premium sound, 30h battery.", category="Audio",
        )
        products.set_item(
            "p1", None,
            name="Mechanical Keyboard", price="$129.99",
            description="Cherry MX, RGB backlight.", category="Input",
        )
        products.set_item(
            "p2", None,
            name="USB-C Hub", price="$49.99",
            description="7-in-1: HDMI, USB-A, SD, ethernet.", category="Accessories",
        )
        products.set_item(
            "p3", None,
            name="4K Monitor", price="$349.99",
            description="27-inch IPS, 144Hz, USB-C.", category="Display",
        )
        data["products"] = products

    def main(self, source):
        head = source.head()
        head.title("Product Catalog — Iterate")
        head.style("""
            .page { font-family: sans-serif; max-width: 700px; margin: 2em auto;
                    color: #333; background: #fff; padding: 1.5em; border-radius: 8px; }
            .catalog { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1em; }
            .card { border: 1px solid #ddd; border-radius: 8px; padding: 1em; }
            .card h3 { margin-top: 0; color: #1e293b; }
            .price { color: #16a34a; font-weight: bold; font-size: 1.2em; }
            .category { color: #666; font-size: 0.85em; text-transform: uppercase; }
            h1 { color: #1e293b; }
        """)

        body = source.body()
        page = body.div(_class="page")
        page.h1("Product Catalog")
        page.p("Each card is generated by iterate — one per product in the data Bag.")

        catalog = page.div(_class="catalog")
        catalog.product_card(iterate="^products")


app = ProductCatalog()
app.run()
html = app.page.render()

output = Path(__file__).with_suffix(".html")
output.write_text(html)
print(html)
print(f"\nSaved to {output}")
